config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"]}

  def avg_review
    if self.reviews.present?
      return (self.reviews.pluck(:rating).sum / self.reviews.count)
    else
      return 0
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all.sort_by { |rest| rest.avg_review }.reverse
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end


  def restaurant_params
    params.require(:restaurant).permit(:name,:address,:phone_number,:category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end


  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="text-center">Restaurants App</h1>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
<br>
  <%= f.input :address %>
<br>
  <%= f.input :phone_number %>
<br>
  <%= f.input :category, :collection => ["chinese", "italian", "japanese", "french", "belgian"]%>
  <%= f.submit "Save Restaurant", class: "btn btn-primary float-right"%>
<% end %>

app/views/restaurants/edit.html.erb
<h2>Edit Restaurant:</h2>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h2>- Restaurants:</h2>
<ul>
  <% @restaurants.each do |restaurant| %>
    <h5 class="restaurants"> <i class="fas fa-utensils"></i>
    <%restaurant.avg_review.times do %>
      <i class="fas fa-star"></i>
    <% end %>
     <%=  link_to restaurant.name, restaurant_path(restaurant), :class => "restaurant" %></h5>
  <% end %>
</ul>
<button type="button" class="btn btn-success float-right"><%= link_to "Create restaurant", new_restaurant_path, :class => "button" %></button>

app/views/restaurants/new.html.erb
<h2>New Restaurant:</h2>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name%></h2>
<br>
<h4>- Info:</h4>
<ul>
  <li>Adress: <%=@restaurant.address %></li>
  <li>Category: <%=@restaurant.category %></li>
  <li>Phone Number: <%=@restaurant.phone_number %></li>
</ul>
<br>
<h4>- Reviews:</h4>
<ul>
  <% @restaurant.reviews.each do |review| %>
      <li><%(review.rating.to_i).times do %>
        <i class="fas fa-star"></i>
      <% end %>
      / <%=review.content%></li>
    <% end %>
</ul>
<br>
<button type="button" class="btn btn-primary"><%= link_to 'Edit', edit_restaurant_path(@restaurant), :class => "button" %></button>
<button type="button" class="btn btn-danger"><%= link_to 'Delete', restaurant_path(@restaurant), method: :delete, data: {confirm: "Are you sure?"}, :class => "button" %></button>
<button type="button" class="btn btn-success float-right"><%= link_to 'Add Review', new_restaurant_review_path(@restaurant), :class => "button" %></button>
<br>
<%=  link_to "Back to list", restaurants_path %>

app/views/reviews/_form.html.erb
<%= simple_form_for [ restaurant, review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, :collection => [0, 1, 2, 3, 4, 5]%>
  <%= f.submit "Submit review", class: "btn btn-primary float-right" %>
<% end %>

app/views/reviews/new.html.erb
<h2>New Review:</h2>
<%= render "form", review: @review, restaurant: @restaurant %>